### ISSUE TITLE
MySql Foreign Key Discussion

### ISSUE THREAD

**Issue by david1403** [togather-2024/togather-backend#3]
MySql Foreign Key Restriction

https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html

* 하고 싶은 것
	* 부모 Table인 member가 있고 자식 테이블인 email_verification 이 있음
	* 부모 Table의 member가 삭제되었을 때(e.g. 회원 탈퇴) email_verification 테이블에서 그 멤버의 정보를 어떻게 처리할 것인가?
		1. 아무 조치도 취하지 않기 (email_verification.email 이 그대로 유지)
		2. email_verification.email의 email 칼럼을 null로 바꿈 (유효하지 않은 멤버를 가리키므로)
		3. email_verification.email에서 해당 회원의 정보를 가지고 있는 row 도 같이 삭제

* Foreign key를 걸면 2, 3에 해당하는 조치가 자동으로 가능하다 -> ON DELETE 옵션을 SET NULL / CASCADE 로 설정하면됨

> 하지만 위 로직이 ***코드로 존재하지 않기 때문에*** 협업하는 개발자가 의도대로 데이터를 다루기 어렵다.

* (위 3가지 옵션중에 3번으로 설정했을 때 )코드로 관리해야 하는 이유.
	* 왜 멤버를 삭제했는데 email_verification 의 데이터도 삭제되는거야?? 그런 로직을 추가한 적이 없는데??
	* 그 로직은 .sql 파일 어딘가에 foreign key 제약 조건으로 있지~~
	* ....?? 그럼 이거 못바꿔...?
	* 바꿀 수는 있지만 foreign key 제약 조건 자체를 변경해야함!
	* 그러면 부모가 삭제될 때 자식이 당연히 삭제되리라고 믿었던 기존 개발자들은....??

* 그래서 위의 3가지 옵션중에서 기본으로는 1로 두고 (아무 조치도 취하지 않음) 코드에서 필요한 테이블의 데이터를 직접 삭제(하거나 조치를 취하는) 로직을 넣고 싶음

* 근데 위의 document 를 보니 foreign key 를 설정할때 1번에 해당하는 옵션이 없는 것으로 보임...

* 결론 ) 일단 DB foreign key 는 추가하지 않고 JPA Entity  연관관계 매핑만 설정해주고, 삭제/업데이트 시에 연관 테이블 데이터 수정은 개발자가 코드로 직접 남기자!

**Comment by sejyom** [comment]
그럼 1:N 관계만 잡아주고, CASCADE 옵션은 별도로 설정하지 않은 상태에서 코드로 핸들링하자는 말씀이시죵?? 옙 반영하겠읍니다 !!
