### ISSUE TITLE
Changes to Member, Email-verification Entities

### ISSUE THREAD

**Issue by sejyom** [togather-2024/togather-backend#6]
## 어떤 기능인가요?

> Member, Email_verification 엔티티 관련 수정 사항.

## 작업 상세 내용

- Email_verification.email -> Email_verification.email_content 필드명 변경.
    - Member 내의 email 필드와 Email_verification 내의 email이 동일하므로 꼬일 위험성을 일절 배제하기 위함.
- Member.email_verified 필드를 Email_verification 엔티티로 이동.
   - 모든 회원은 이메일 인증이 완료된 이후 가입 처리가 가능하기 때문에 member 엔티티에서의 필요성을 느끼지 못함.
   - Email_verification 엔티티에서 동일 email_content를 가리키는 여러 레코드가 있을 수 있기 때문에 처리 완료된 레코드는 이 쪽에서 잡아주는 게 더 적합하다고 판단.

**Comment by david1403** [comment]
1. email_content 라는 칼럼은 "이메일 내용"을 담고 있어서 '이메일 수신자(이메일 인증 대상)'이라는 칼럼을 담아야하는 email 칼럼을 가지는게 더 적합해 보입니다. 칼럼 이름이 동일해서 혼동이 된다면 receiver_email_address 정도로 바꾸는건 어떨까요..?
2. email_verified 는 '이메일 인증을 통과했음' 을 나타내는 칼럼인데, 회원한테 붙는 특성이지 개개인 이메일 인증이 성공했는지 실패했는지를 email_verification DB에는 저장할 필요가 없어 보입니다. 회원이 짧은 시간내에 여러 인증을 시도했다고 하더라도, 가장 최근의 인증코드를 기준으로 비교하면 될 것 같아요. 그래서 차라리 member.email_verified 칼럼을 없애는게 좋아보입니다.

**Comment by sejyom** [comment]
1. 좋습니다! receiver_email_address로 변경하겠습니다
2. 저도 굳이 저장해야 하나 싶었는데, 테이블화 한 것 자체가 로그식으로 남기기 위함으로 이해해서 이 부분도 필요한 건가 했습니다. 그럼 email_verified 컬럼은 삭제하겠습니다
