### ISSUE TITLE
About Enum.valueOf()

### ISSUE THREAD

**Issue by david1403** [togather-2024/togather-backend#8]
<img width="389" alt="image" src="https://github.com/togather-2024/togather-backend/assets/37106166/7d4771ca-ac45-47d0-8bce-40be0452ded9">

Role enum 파일의 일부입니다.
valueOf() 함수는 String 으로 Role 을 반환하기 위한 함수로 보입니다. 
Role.valueOf("GUEST") -> Role.GUEST 를 의도하신 것 같아요.

하지만 Enum.valueOf()는 값에 해당하는 Enum이 없다면 예외를 던집니다. 즉 Role.valueOf("Hello") 가 들어오면 exception이 발생합니다.
https://docs.oracle.com/javase/8/docs/api/java/lang/Enum.html
<img width="1670" alt="image" src="https://github.com/togather-2024/togather-backend/assets/37106166/d782620a-a13c-4829-a251-3ecc8a78c0bc">

이 케이스를 어떻게 핸들링하면 좋을까요?

**Comment by david1403** [comment]
ExceptionHandler 를 두어 IllegalArgumentException 을 Catch 해서 의도하지 않은 파라미터(role = hello와 같은..)로 입력이 되었으면 예외를 client로 알리자는 말씀이시죠?
그런데 ExceptionHandler.. 로 IllegalArgumentException 를 Catch 한다 하더라도, 로직 상에서 Role 이라는 Enum 파일에서 발생한 IllegalArgumentException 인지, 혹은 다른 곳에서 발생한 IllegalArgumentException인지를 구분할 수 있을까요?
다른 곳에서 IllegalArgumentException 이 발생했는데 Front에 "Role이 잘못 입력되었어요~" 와 같은 메시지를 전달하면 안될 것 같아서요.

**Comment by sejyom** [comment]
그럼 ErrorCode 클래스를 정의하여 사용하는 거 어떨까요?
예외의 종류나 원인을 식별하기에도 좋고, 클라이언트에게 적절한 메시지도 제공할 수 있을 것 같아요!

**Comment by david1403** [comment]
resolved by using static block code : )
